language: c

env:
  global:
    # coverity token
    - secure: ""
  matrix:
    # standard builds
    - CC=gcc
    - CC=clang
    # cross-compile using mingw
    - CC= PLATFORM="mingw32" ARCH="x86"
    - CC= PLATFORM="mingw32" ARCH="x86_64"

script: ./travis-ci-build.sh

before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove -qq -y mingw32
  - sudo apt-get install -q -y mingw-w64

notifications:
  irc: "irc.freenode.org#mecwerks"
  on_success: change
  on_failure: always

addons:
  coverity_scan:
    project:
      name: "mecwerks/revamp"
      description: "Build submitted via Travis CI"
    build_command_prepend: "make clean"
    build_command: "make release"
    branch_pattern: master
